name: Compile APK

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.25.0' # Matches the version in pubspec.yaml
          channel: 'stable'

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.84.1'
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android, i686-linux-android

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen@^2.0.0-dev.0

      - name: Decode key.properties
        if: ${{ env.ANDROID_KEY_PROPERTIES != '' }}
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: echo "$ANDROID_KEY_PROPERTIES" | base64 -d > app/android/key.properties

      - name: Decode android-keystore.jks
        if: ${{ env.ANDROID_KEY_STORE != '' }}
        env:
          ANDROID_KEY_STORE: ${{ secrets.ANDROID_KEY_STORE }}
        run: |
          mkdir -p secrets
          echo "$ANDROID_KEY_STORE" | base64 -d > secrets/android-keystore.jks

      - name: Fetch Flutter Dependencies
        working-directory: app
        run: flutter pub get

      - name: Build Debug APK for Testing
        working-directory: app
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gravitysend-debug-apk
          path: app/build/app/outputs/flutter-apk/app-debug.apk
